import { GuesthouseListItemProps } from "@/types/guesthouse";
import { ReviewListItemProps } from "@/types/reviews";

export const mockdata_recruits: GuesthouseListItemProps[] = [
    {
        employmentId: 1,
        title: "결 게스트하우스 스탭모집",
        image: "/images/guesthouse3.png",
        hashtagName: ["활기찬", "힐링", "자연", "바다"],
        content: "바다 근처 힙한 게스트 하우스",
        locationName: "함덕해수욕장",
        sex: "male",
        personNum: 2,
        recruitmentEnd: "2025-05-13",
    },
    {
        employmentId: 2,
        title: "오션뷰 게스트하우스",
        image: "/images/guesthouse3.png",
        hashtagName: ["뷰맛집", "바다", "프라이빗"],
        content: "바다가 보이는 오션뷰 숙소",
        locationName: "협재",
        sex: "female",
        personNum: 1,
        closed: true,
        recruitmentEnd: "2025-05-13",
    },
    {
        employmentId: 3,
        title: "소소한 쉼터",
        image: "/images/guesthouse3.png",
        hashtagName: ["힐링", "자연"],
        content: "마음이 편안해지는 조용한 숙소",
        locationName: "성산읍",
        sex: "male",
        personNum: 2,
        recruitmentEnd: "2025-05-13",
    },
    {
        employmentId: 4,
        title: "오션뷰 게스트하우스",
        image: "/images/guesthouse3.png",
        hashtagName: ["뷰맛집", "바다", "프라이빗"],
        content: "바다가 보이는 오션뷰 숙소",
        locationName: "협재",
        sex: "female",
        personNum: 1,
        closed: true,
        recruitmentEnd: "2025-05-13",
    },
    {
        employmentId: 5,
        title: "소소한 쉼터",
        image: "/images/guesthouse3.png",
        hashtagName: ["힐링", "자연"],
        content: "마음이 편안해지는 조용한 숙소",
        locationName: "성산읍",
        sex: "male",
        personNum: 2,
        recruitmentEnd: "2025-05-13",
    },
    {
        employmentId: 6,
        title: "오션뷰 게스트하우스",
        image: "/images/guesthouse3.png",
        hashtagName: ["뷰맛집", "바다", "프라이빗"],
        content: "바다가 보이는 오션뷰 숙소",
        locationName: "협재",
        sex: "female",
        personNum: 1,
        closed: true,
        recruitmentEnd: "2025-05-13",
    },
    {
        employmentId: 7,
        title: "소소한 쉼터",
        image: "/images/guesthouse3.png",
        hashtagName: ["힐링", "자연"],
        content: "마음이 편안해지는 조용한 숙소",
        locationName: "성산읍",
        sex: "male",
        personNum: 2,
        recruitmentEnd: "2025-05-13",
    },
    {
        employmentId: 8,
        title: "오션뷰 게스트하우스",
        image: "/images/guesthouse3.png",
        hashtagName: ["뷰맛집", "바다", "프라이빗"],
        content: "바다가 보이는 오션뷰 숙소",
        locationName: "협재",
        sex: "female",
        personNum: 3,
        closed: true,
        recruitmentEnd: "2025-05-13",
    },
    // api 명세에 맞게 mockdata 임시 수정
];

export const mockdata_reviews: ReviewListItemProps = {
    hasNext: false,
    countReview: 3,
    averageRating: 4.5,
    allReviewInfoDTOS: [
        {
            reviewId: 1,
            rating: 4.8,
            title: "올레 게스트하우스",
            nickName: "테스트유저111",
            images: [],
            review: "깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!",
            disclosure: true,
            reviewComment:
                "감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)",
            reviewDate: 1747900000,
            reviewCommentDate: 1747900000,
            hostNickName: "호스트",
        },
        {
            reviewId: 2,
            rating: 2.2,
            title: "올레 게스트하우스 공고2",
            nickName: "테스트22유저22",
            images: [
                "https://media.istockphoto.com/id/1931942677/ko/%EB%B2%A1%ED%84%B0/%EC%96%B4%EB%A6%B0-%EC%95%84%EB%93%A4%EC%97%90%EA%B2%8C-%ED%82%A4%EC%8A%A4%ED%95%98%EB%8A%94-%ED%96%89%EB%B3%B5%ED%95%9C-%EC%97%84%EB%A7%88%EC%99%80-%EC%95%84%EB%B9%A0.jpg?s=612x612&w=is&k=20&c=p97JRWHfdsRYAlu5Cnx9tvCUl_jBSTxyXedZLRUUD_Q=",
                "https://media.istockphoto.com/id/1931942677/ko/%EB%B2%A1%ED%84%B0/%EC%96%B4%EB%A6%B0-%EC%95%84%EB%93%A4%EC%97%90%EA%B2%8C-%ED%82%A4%EC%8A%A4%ED%95%98%EB%8A%94-%ED%96%89%EB%B3%B5%ED%95%9C-%EC%97%84%EB%A7%88%EC%99%80-%EC%95%84%EB%B9%A0.jpg?s=612x612&w=is&k=20&c=p97JRWHfdsRYAlu5Cnx9tvCUl_jBSTxyXedZLRUUD_Q=",
                "https://media.istockphoto.com/id/1931942677/ko/%EB%B2%A1%ED%84%B0/%EC%96%B4%EB%A6%B0-%EC%95%84%EB%93%A4%EC%97%90%EA%B2%8C-%ED%82%A4%EC%8A%A4%ED%95%98%EB%8A%94-%ED%96%89%EB%B3%B5%ED%95%9C-%EC%97%84%EB%A7%88%EC%99%80-%EC%95%84%EB%B9%A0.jpg?s=612x612&w=is&k=20&c=p97JRWHfdsRYAlu5Cnx9tvCUl_jBSTxyXedZLRUUD_Q=",
            ],
            review: "깔끔하고 친절했어요!깔끔하고 친절했어요!",
            disclosure: false,
            reviewComment: null,
            reviewDate: 1747900000,
            reviewCommentDate: 1747900000,
            hostNickName: "호스트",
        },
        {
            reviewId: 3,
            rating: 4.2,
            title: "게스트하우스 중 최고",
            nickName: "저는테스트유저일까요?",
            images: [],
            review: "흠",
            disclosure: true,
            reviewComment: null,
            reviewDate: 1747900000,
            reviewCommentDate: 1747900000,
            hostNickName: "호스트",
        },
    ],
};
