import { GuesthouseListItemProps } from "@/types/guesthouse";
import { ReviewListItemProps } from "@/types/reviews";

export const mockdata_recruits: GuesthouseListItemProps[] = [
    // {
    //     id: 1,
    //     title: "결 게스트하우스 스탭모집",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["활기찬", "힐링", "자연", "바다"],
    //     description: "바다 근처 힙한 게스트 하우스",
    //     location: "함덕해수욕장",
    //     personnel: "남자 2명 모집",
    // },
    // {
    //     id: 2,
    //     title: "오션뷰 게스트하우스",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["뷰맛집", "바다", "프라이빗"],
    //     description: "바다가 보이는 오션뷰 숙소",
    //     location: "협재",
    //     personnel: "여자 1명 모집",
    //     closed: true,
    // },
    // {
    //     id: 3,
    //     title: "소소한 쉼터",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["힐링", "자연"],
    //     description: "마음이 편안해지는 조용한 숙소",
    //     location: "성산읍",
    //     personnel: "남자 2명 모집",
    // },
    // {
    //     id: 4,
    //     title: "숲뷰 게스트하우스",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["뷰맛집", "숲", "프라이빗"],
    //     description: "숲 보이는 시원한 숙소",
    //     location: "한라산 자락",
    //     personnel: "여자 1명 모집",
    //     closed: true,
    // },
    // {
    //     id: 5,
    //     title: "바람의 언덕 게스트하우스",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["풍경", "자연", "한적함"],
    //     description: "한적하고 바람 부는 언덕에 위치한 감성 숙소",
    //     location: "애월",
    //     personnel: "혼성 1명 모집",
    // },
    // {
    //     id: 6,
    //     title: "감귤향 게스트하우스",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["감성", "자연", "조용한"],
    //     description: "감귤 농장 옆 조용한 힐링 스팟",
    //     location: "남원읍",
    //     personnel: "여자 2명 모집",
    // },
    // {
    //     id: 7,
    //     title: "달빛 게스트하우스",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["야경", "조용함", "감성숙소"],
    //     description: "달빛 아래에서의 힐링 타임을 경험하세요",
    //     location: "제주시 구좌읍",
    //     personnel: "남자 1명 모집",
    //     closed: true,
    // },
    // {
    //     id: 8,
    //     title: "카페뷰 게스트하우스",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["카페거리", "바다뷰", "젊음"],
    //     description: "카페와 바다가 함께 있는 핫플레이스",
    //     location: "이호테우 해변",
    //     personnel: "여자 1명 모집",
    // },
    // {
    //     id: 9,
    //     title: "고요한 아침의 게스트하우스",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["조용한", "숲", "힐링"],
    //     description: "고요한 아침을 맞이할 수 있는 평화로운 공간",
    //     location: "한림읍",
    //     personnel: "혼성 2명 모집",
    // },
    // {
    //     id: 10,
    //     title: "제주 오름뷰 스테이",
    //     imageUrl: "/images/guesthouse3.png",
    //     tags: ["오름", "풍경", "자연친화"],
    //     description: "오름이 내려다보이는 탁 트인 풍경의 숙소",
    //     location: "표선면",
    //     personnel: "여자 1명 모집",
    // },
];

export const mockdata_reviews: ReviewListItemProps = {
    hasNext: false,
    countReview: 3,
    averageRating: 4.5,
    allReviewInfoDTOS: [
        //     {
        //         reviewId: 1,
        //         rating: 4.8,
        //         title: "올레 게스트하우스",
        //         nickName: "테스트유저111",
        //         images: [],
        //         review: "깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!깔끔하고 친절했어요!",
        //         disclosure: true,
        //         reviewComment:
        //             "감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)감사합니다! 또 놀러오세요 :)",
        //         reviewDate: 1747900000,
        //         reviewCommentDate: 1747900000,
        //         hostNickName: "호스트",
        //     },
        //     {
        //         reviewId: 2,
        //         rating: 2.2,
        //         title: "올레 게스트하우스 공고2",
        //         nickName: "테스트22유저22",
        //         images: [
        //             "https://media.istockphoto.com/id/1931942677/ko/%EB%B2%A1%ED%84%B0/%EC%96%B4%EB%A6%B0-%EC%95%84%EB%93%A4%EC%97%90%EA%B2%8C-%ED%82%A4%EC%8A%A4%ED%95%98%EB%8A%94-%ED%96%89%EB%B3%B5%ED%95%9C-%EC%97%84%EB%A7%88%EC%99%80-%EC%95%84%EB%B9%A0.jpg?s=612x612&w=is&k=20&c=p97JRWHfdsRYAlu5Cnx9tvCUl_jBSTxyXedZLRUUD_Q=",
        //             "https://media.istockphoto.com/id/1931942677/ko/%EB%B2%A1%ED%84%B0/%EC%96%B4%EB%A6%B0-%EC%95%84%EB%93%A4%EC%97%90%EA%B2%8C-%ED%82%A4%EC%8A%A4%ED%95%98%EB%8A%94-%ED%96%89%EB%B3%B5%ED%95%9C-%EC%97%84%EB%A7%88%EC%99%80-%EC%95%84%EB%B9%A0.jpg?s=612x612&w=is&k=20&c=p97JRWHfdsRYAlu5Cnx9tvCUl_jBSTxyXedZLRUUD_Q=",
        //             "https://media.istockphoto.com/id/1931942677/ko/%EB%B2%A1%ED%84%B0/%EC%96%B4%EB%A6%B0-%EC%95%84%EB%93%A4%EC%97%90%EA%B2%8C-%ED%82%A4%EC%8A%A4%ED%95%98%EB%8A%94-%ED%96%89%EB%B3%B5%ED%95%9C-%EC%97%84%EB%A7%88%EC%99%80-%EC%95%84%EB%B9%A0.jpg?s=612x612&w=is&k=20&c=p97JRWHfdsRYAlu5Cnx9tvCUl_jBSTxyXedZLRUUD_Q=",
        //         ],
        //         review: "깔끔하고 친절했어요!깔끔하고 친절했어요!",
        //         disclosure: false,
        //         reviewComment: null,
        //         reviewDate: 1747900000,
        //         reviewCommentDate: 1747900000,
        //         hostNickName: "호스트",
        //     },
        //     {
        //         reviewId: 3,
        //         rating: 4.2,
        //         title: "게스트하우스 중 최고",
        //         nickName: "저는테스트유저일까요?",
        //         images: [],
        //         review: "흠",
        //         disclosure: true,
        //         reviewComment: null,
        //         reviewDate: 1747900000,
        //         reviewCommentDate: 1747900000,
        //         hostNickName: "호스트",
        //     },
    ],
};
